/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/sync/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync Images
         * @description Idempotent upsert. Replaces tags wholesale per image (simpler than
         *     diffing tag rows; tag count per image is small, ≤ 30 typical).
         */
        post: operations["sync_images_internal_sync_images_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/sync/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync Projects */
        post: operations["sync_projects_internal_sync_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/sync/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync Api Keys */
        post: operations["sync_api_keys_internal_sync_api_keys_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/sync/deletes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync Deletes
         * @description Apply tombstone events: when local user deletes something, cloud
         *     drops it too (otherwise UGC keeps matching ghost rows).
         */
        post: operations["sync_deletes_internal_sync_deletes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/sync/synonyms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync Synonyms
         * @description Replace the synonym dict file. Hot-reloads the in-process cache via
         *     the version bump that match_synonyms._write does.
         */
        post: operations["sync_synonyms_internal_sync_synonyms_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/sync/tag-schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync Tag Schema
         * @description Replace the tag schema file.
         */
        post: operations["sync_tag_schema_internal_sync_tag_schema_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/sync/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync Config
         * @description Merge incoming settings into cloud's config.json. Only the keys
         *     actually sent are touched — existing keys not in the payload are
         *     preserved (so partial pushes don't wipe what we already have).
         */
        post: operations["sync_config_internal_sync_config_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/sync/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sync Health
         * @description Liveness endpoint for the local sync_worker to confirm cloud is up.
         */
        get: operations["sync_health_internal_sync_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/open-api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_open_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/open-api/v1/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Images */
        get: operations["list_images_open_api_v1_images_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/open-api/v1/images/{image_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Image */
        get: operations["get_image_open_api_v1_images__image_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/open-api/v1/images/{image_id}/derivatives": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Derivatives
         * @description All images that were generated from this seed (parent_id chain).
         */
        get: operations["list_derivatives_open_api_v1_images__image_id__derivatives_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/open-api/v1/images/{image_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Image File */
        get: operations["get_image_file_open_api_v1_images__image_id__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/open-api/v1/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tags */
        get: operations["list_tags_open_api_v1_tags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/open-api/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stats */
        get: operations["stats_open_api_v1_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/open-api/v1/matrix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Coverage Matrix
         * @description Cell counts for `row × col` tag dimensions.
         */
        get: operations["coverage_matrix_open_api_v1_matrix_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/open-api/v1/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Batches Public */
        get: operations["list_batches_public_open_api_v1_batches_get"];
        put?: never;
        /**
         * Submit Batch Public
         * @description Scope: generate:write — most H5 keys should not be granted this.
         */
        post: operations["submit_batch_public_open_api_v1_batches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/open-api/v1/batches/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Batch Public */
        get: operations["get_batch_public_open_api_v1_batches__batch_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/open-api/v1/images/match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Match Images
         * @description Match a piece of text against the image library.
         *
         *     Returns up to `limit` images ranked by:
         *       - cross-modal embedding similarity (Ark vision, same space as text)
         *       - tag dimension hits extracted from the text via jieba + tag schema
         *       - blur quality, business rules, diversity
         *
         *     See match_strategy.STRATEGY_PRESETS for weight defaults; pass
         *     `weights` to override per-call.
         */
        post: operations["match_images_open_api_v1_images_match_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/open-api/v1/images/{image_id}/track-usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Track Usage
         * @description UGC client reports that an image was chosen / displayed. Drives
         *     precision telemetry and (later) weight tuning.
         *
         *     Idempotency: client SHOULD pass request_id so duplicates can be merged
         *     in analysis. Server stores every call as a separate row to keep the
         *     write hot path fast.
         */
        post: operations["track_usage_open_api_v1_images__image_id__track_usage_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/open-api/v1/images/similar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Find Similar Images
         * @description Find images visually similar to a seed. Reuses the same embedding
         *     matrix and post-processing pipeline as /images/match — only the query
         *     vector source differs (image embedding instead of text embedding).
         */
        post: operations["find_similar_images_open_api_v1_images_similar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/open-api/v1/match/strategies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Strategies
         * @description Static list of strategy presets the client can pick from.
         */
        get: operations["list_strategies_open_api_v1_match_strategies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/open-api/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api List Images
         * @description List images with filters. Returns JSON with CDN-ready URLs.
         */
        get: operations["api_list_images_open_api_images_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/open-api/images/{image_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Get Image
         * @description Get image metadata + tags.
         */
        get: operations["api_get_image_open_api_images__image_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/open-api/images/{image_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Get Image File
         * @description Serve image file. Optional size param for thumbnail (128/300/800).
         */
        get: operations["api_get_image_file_open_api_images__image_id__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/open-api/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api List Tags
         * @description List tag distribution for a project.
         */
        get: operations["api_list_tags_open_api_tags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/open-api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Stats
         * @description Quick stats for external dashboards.
         */
        get: operations["api_stats_open_api_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiKeySyncBody */
        ApiKeySyncBody: {
            /** Id */
            id: string;
            /** Key Id */
            key_id: string;
            /** Key Secret Hash */
            key_secret_hash: string;
            /** Name */
            name: string;
            /**
             * Client Type
             * @default server
             */
            client_type: string | null;
            /** Allowed Origins */
            allowed_origins?: string[] | null;
            /** Allowed Ips */
            allowed_ips?: string[] | null;
            /** Scopes */
            scopes?: string[] | null;
            /** Rate Limit */
            rate_limit?: {
                [key: string]: unknown;
            } | null;
            /** Expires At */
            expires_at?: string | null;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /** BatchSubmitBody */
        BatchSubmitBody: {
            /** Name */
            name: string;
            /** Task Type */
            task_type: string;
            /** Seed Image Ids */
            seed_image_ids: string[];
            /** Prompt Ids */
            prompt_ids: string[];
            /** Project Id */
            project_id: string;
            /**
             * Concurrency
             * @default 10
             */
            concurrency: number;
            /**
             * Max Retry
             * @default 3
             */
            max_retry: number;
            /** Budget Usd */
            budget_usd?: number | null;
        };
        /** BulkApiKeysBody */
        BulkApiKeysBody: {
            /** Api Keys */
            api_keys: components["schemas"]["ApiKeySyncBody"][];
        };
        /** BulkImagesBody */
        BulkImagesBody: {
            /** Images */
            images: components["schemas"]["ImageSyncBody"][];
        };
        /** BulkProjectsBody */
        BulkProjectsBody: {
            /** Projects */
            projects: components["schemas"]["ProjectSyncBody"][];
        };
        /**
         * ConfigSyncBody
         * @description Selective config push. Local should send ONLY the keys the cloud
         *     needs (embedding provider + relays). Never push OSS access keys or
         *     generation provider keys — cloud doesn't upload or generate.
         */
        ConfigSyncBody: {
            /** Settings */
            settings: {
                [key: string]: unknown;
            };
        };
        /** DeleteEventsBody */
        DeleteEventsBody: {
            /**
             * Images
             * @default []
             */
            images: string[];
            /**
             * Projects
             * @default []
             */
            projects: string[];
            /**
             * Api Keys
             * @default []
             */
            api_keys: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImageSyncBody */
        ImageSyncBody: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** File Path */
            file_path: string;
            /** File Name */
            file_name: string;
            /** File Hash */
            file_hash?: string | null;
            /** Phash */
            phash?: string | null;
            /** File Size Kb */
            file_size_kb?: number | null;
            /** Width */
            width?: number | null;
            /** Height */
            height?: number | null;
            /** Blur Score */
            blur_score?: number | null;
            /** Brightness */
            brightness?: number | null;
            /** Quality Status */
            quality_status?: string | null;
            /** Reject Reason */
            reject_reason?: string | null;
            /**
             * Is Kept
             * @default true
             */
            is_kept: boolean | null;
            /** Tag Status */
            tag_status?: string | null;
            /** Description */
            description?: string | null;
            /** Source Type */
            source_type?: string | null;
            /** Relative Dir */
            relative_dir?: string | null;
            /** Parent Id */
            parent_id?: string | null;
            /** Rotated File Path */
            rotated_file_path?: string | null;
            /** Orient Status */
            orient_status?: string | null;
            /** Cdn Path */
            cdn_path?: string | null;
            /** Embedding */
            embedding?: number[] | null;
            /** Embedding Model */
            embedding_model?: string | null;
            /** Text Search Blob */
            text_search_blob?: string | null;
            /** Generation Metadata */
            generation_metadata?: {
                [key: string]: unknown;
            } | null;
            /** Tagged At */
            tagged_at?: string | null;
            /** Tag Provider */
            tag_provider?: string | null;
            /**
             * Tags
             * @default []
             */
            tags: {
                [key: string]: unknown;
            }[];
        };
        /** MatchBody */
        MatchBody: {
            /** Text */
            text: string;
            /**
             * Limit
             * @default 8
             */
            limit: number;
            filters?: components["schemas"]["MatchFiltersBody"] | null;
            scope?: components["schemas"]["MatchScopeBody"] | null;
            /**
             * Strategy
             * @default balanced
             */
            strategy: string | null;
            /** Weights */
            weights?: {
                [key: string]: unknown;
            } | null;
            /**
             * Diversity
             * @default balanced
             */
            diversity: string | null;
            /**
             * Randomness
             * @default 0
             */
            randomness: number | null;
            /** Exclude Ids */
            exclude_ids?: string[] | null;
            /**
             * Unique Per Source
             * @default true
             */
            unique_per_source: boolean | null;
            /**
             * No People
             * @default true
             */
            no_people: boolean | null;
        };
        /** MatchFiltersBody */
        MatchFiltersBody: {
            /** Scene */
            scene?: string[] | null;
            /** Facility */
            facility?: string[] | null;
            /** Season */
            season?: string[] | null;
            /** Weather */
            weather?: string[] | null;
            /** Angle */
            angle?: string[] | null;
            /** People */
            people?: string[] | null;
            /** Usage */
            usage?: string[] | null;
            /** Exclude Tags */
            exclude_tags?: {
                [key: string]: unknown;
            } | null;
            /** Source Type */
            source_type?: string | null;
            /** Project Id */
            project_id?: string | null;
            /** Folder Prefix */
            folder_prefix?: string | null;
            /** Prompt Ids */
            prompt_ids?: string[] | null;
            /** Parent Ids */
            parent_ids?: string[] | null;
            /** Image Ids */
            image_ids?: string[] | null;
        };
        /**
         * MatchScopeBody
         * @description How candidates should be distributed across projects.
         *
         *     `primary_project_id` is the call's home project (typically derived from
         *     the API key's binding; the playground passes the operator's currently
         *     selected project). The auto-quota algorithm gives this project at least
         *     75% of slots and only lets other projects in when the text is genuinely
         *     relevant to them.
         *
         *     `force_single_project` is a debug-only override that disables all
         *     cross-project leakage. The playground exposes this as 「强制单项目」.
         */
        MatchScopeBody: {
            /** Primary Project Id */
            primary_project_id?: string | null;
            /**
             * Force Single Project
             * @default false
             */
            force_single_project: boolean | null;
        };
        /** ProjectSyncBody */
        ProjectSyncBody: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Originals Path */
            originals_path: string;
            /** Workspace Path */
            workspace_path: string;
            /** Color */
            color?: string | null;
        };
        /** SimilarBody */
        SimilarBody: {
            /** Seed Image Id */
            seed_image_id: string;
            /**
             * Limit
             * @default 8
             */
            limit: number;
            filters?: components["schemas"]["MatchFiltersBody"] | null;
            /**
             * Diversity
             * @default balanced
             */
            diversity: string | null;
        };
        /**
         * SynonymsSyncBody
         * @description Whole-dictionary replace (small payload, simpler than diff sync).
         */
        SynonymsSyncBody: {
            /** Entries */
            entries: {
                [key: string]: string;
            };
            /**
             * Version
             * @default 0
             */
            version: number;
        };
        /** TagSchemaSyncBody */
        TagSchemaSyncBody: {
            /** Schema */
            schema: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
        };
        /** TrackUsageBody */
        TrackUsageBody: {
            /** Request Id */
            request_id?: string | null;
            /** Text */
            text?: string | null;
            /** Rank */
            rank?: number | null;
            /** Score */
            score?: number | null;
            /**
             * Was Chosen
             * @default true
             */
            was_chosen: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    sync_images_internal_sync_images_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkImagesBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_projects_internal_sync_projects_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkProjectsBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_api_keys_internal_sync_api_keys_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkApiKeysBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_deletes_internal_sync_deletes_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteEventsBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_synonyms_internal_sync_synonyms_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SynonymsSyncBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_tag_schema_internal_sync_tag_schema_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagSchemaSyncBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_config_internal_sync_config_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigSyncBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_health_internal_sync_health_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_open_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_images_open_api_v1_images_get: {
        parameters: {
            query?: {
                project_id?: string | null;
                source_type?: string | null;
                scene?: string[] | null;
                season?: string[] | null;
                folder?: string | null;
                folder_prefix?: string | null;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_image_open_api_v1_images__image_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                image_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_derivatives_open_api_v1_images__image_id__derivatives_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                image_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_image_file_open_api_v1_images__image_id__file_get: {
        parameters: {
            query?: {
                size?: number | null;
            };
            header?: never;
            path: {
                image_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tags_open_api_v1_tags_get: {
        parameters: {
            query?: {
                project_id?: string | null;
                dimension?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stats_open_api_v1_stats_get: {
        parameters: {
            query?: {
                project_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    coverage_matrix_open_api_v1_matrix_get: {
        parameters: {
            query: {
                project_id: string;
                row?: string;
                col?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_batches_public_open_api_v1_batches_get: {
        parameters: {
            query?: {
                project_id?: string | null;
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_batch_public_open_api_v1_batches_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchSubmitBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_batch_public_open_api_v1_batches__batch_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    match_images_open_api_v1_images_match_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    track_usage_open_api_v1_images__image_id__track_usage_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                image_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrackUsageBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    find_similar_images_open_api_v1_images_similar_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimilarBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_strategies_open_api_v1_match_strategies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    api_list_images_open_api_images_get: {
        parameters: {
            query?: {
                project_id?: string | null;
                source_type?: string | null;
                scene?: string[] | null;
                season?: string[] | null;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_get_image_open_api_images__image_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                image_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_get_image_file_open_api_images__image_id__file_get: {
        parameters: {
            query?: {
                size?: number | null;
            };
            header?: never;
            path: {
                image_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_list_tags_open_api_tags_get: {
        parameters: {
            query?: {
                project_id?: string | null;
                dimension?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_stats_open_api_stats_get: {
        parameters: {
            query?: {
                project_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
