import { useCallback, useEffect, useRef, useState } from 'react'
import { useInfiniteQuery } from '@tanstack/react-query'
import { toast } from 'sonner'
import { api } from '@/lib/api'
import { JustifiedGrid } from './JustifiedGrid'
import { Check, Loader2, Minus, Plus } from 'lucide-react'
import { cn } from '@/lib/utils'
import type { ImageRecord } from '@/lib/types'

const PAGE_SIZE = 120
const ROW_HEIGHT_MIN = 120
const ROW_HEIGHT_MAX = 320
const ROW_HEIGHT_STEP = 20

interface ImageGridProps {
  projectId: string
  search?: string
  status?: string
  sourceType?: string
  folder?: string | null            // null = no filter; "" = root; "xxx" = that folder (includes sub)
  /** Multi-value tag filters per dimension. Within dimension OR, across AND. */
  tagFilters?: Partial<Record<
    'scene' | 'facility' | 'season' | 'weather' | 'angle' | 'people' | 'usage'
    | 'style' | 'mood' | 'palette' | 'theme' | 'composition',
    string[]
  >>
  /** Filter to images generated by a specific prompt (matches
   * generation_metadata.prompt_id on the backend). */
  promptId?: string
  /** Filter to images whose parent_id == this id (i.e. derivatives
   * of a given seed). */
  parentId?: string
  selectedIds: Set<string>
  onToggleSelect: (id: string) => void
  onSelectAll?: (ids: string[]) => void
  /** Active = the inspector is currently showing this image. */
  activeId?: string | null
  /** Single-click: pick into inspector. List is the full ordered set so the
   * caller can resolve current index for keyboard navigation. */
  onClickImage: (image: ImageRecord, list?: ImageRecord[]) => void
  /** Double-click: open lightbox preview. */
  onDoubleClickImage?: (image: ImageRecord, list?: ImageRecord[]) => void
}

export function ImageGrid({
  projectId, search, status, sourceType, folder, tagFilters, promptId, parentId,
  selectedIds, onToggleSelect, onSelectAll, onClickImage, onDoubleClickImage, activeId,
}: ImageGridProps) {
  const selectionMode = selectedIds.size > 0
  const [rowHeight, setRowHeight] = useState(200)

  // Build the full param object once and reuse for list / listIds queries
  // so we can't drift between them.
  const baseParams = {
    project_id: projectId,
    search: search || undefined,
    status: status && status !== 'all' ? status : undefined,
    source_type: sourceType && sourceType !== 'all' ? sourceType : undefined,
    ...(tagFilters || {}),
    prompt_id: promptId || undefined,
    parent_id: parentId || undefined,
    ...(folder === ''
      ? { folder: '' }
      : folder
        ? { folder_prefix: folder }
        : {}),
  }

  // Stable cache key for tagFilters/promptId — JSON.stringify keeps things
  // simple without introducing a deep-equal hook.
  const filterKey = JSON.stringify({ tagFilters, promptId, parentId })

  const { data, fetchNextPage, hasNextPage, isLoading } = useInfiniteQuery({
    queryKey: ['images', projectId, search, status, sourceType, folder, filterKey],
    queryFn: ({ pageParam = 0 }) =>
      api.images.list({
        ...baseParams,
        offset: pageParam as number,
        limit: PAGE_SIZE,
      }),
    getNextPageParam: (lastPage, pages) =>
      lastPage.items.length === PAGE_SIZE ? pages.length * PAGE_SIZE : undefined,
    initialPageParam: 0,
  })

  const allImages = data?.pages.flatMap((p) => p.items) ?? []
  const total = data?.pages[0]?.total ?? 0
  const [selectingAll, setSelectingAll] = useState(false)

  // Toolbar checkbox: toggle current page (loaded so far) selection.
  const handleSelectAll = useCallback(() => {
    if (onSelectAll) onSelectAll(allImages.map((img) => img.id))
  }, [allImages, onSelectAll])

  // "选中全部 N 张" — fetches every id matching the active filter from the
  // backend in one shot, bypassing pagination.
  const handleSelectAllMatching = useCallback(async () => {
    if (!onSelectAll) return
    setSelectingAll(true)
    try {
      const res = await api.images.listIds(baseParams)
      onSelectAll(res.ids)
      toast.success(`已选中匹配筛选条件的全部 ${res.count.toLocaleString()} 张图片`)
    } catch (e: any) {
      toast.error(`全选失败：${e?.message || e}`)
    } finally {
      setSelectingAll(false)
    }
    // Re-build deps via filterKey so callback isn't recreated each render
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [onSelectAll, projectId, search, status, sourceType, folder, filterKey])

  if (isLoading) {
    return (
      <div className="flex flex-wrap gap-2">
        {Array.from({ length: 12 }).map((_, i) => (
          <div
            key={i}
            className="rounded-md bg-foreground/[0.03] animate-pulse"
            style={{ height: rowHeight, width: rowHeight * (1 + (i % 3) * 0.3) }}
          />
        ))}
      </div>
    )
  }

  if (allImages.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center h-64 text-foreground/30 text-[13px]">
        <p>暂无图片</p>
        <p className="text-[12px] mt-1">在流水线中选择目录并执行扫描以导入图片</p>
      </div>
    )
  }

  const allSelected = allImages.length > 0 && allImages.every((img) => selectedIds.has(img.id))
  const someSelected = selectedIds.size > 0 && !allSelected

  return (
    <div>
      {/* Toolbar */}
      <div className="flex items-center gap-3 mb-3">
        <button
          onClick={handleSelectAll}
          className={cn(
            'w-4 h-4 rounded-sm border flex items-center justify-center transition-all',
            allSelected
              ? 'bg-accent border-accent text-white'
              : someSelected
                ? 'bg-accent/30 border-accent text-white'
                : 'border-foreground/20 hover:border-foreground/40',
          )}
          title={allSelected ? '取消全选' : '全选当前页'}
        >
          {(allSelected || someSelected) && <Check size={10} strokeWidth={3} />}
        </button>
        <span className="text-[12px] text-foreground/45 whitespace-nowrap">
          {selectedIds.size > 0
            ? `已选 ${selectedIds.size.toLocaleString()} / ${total.toLocaleString()} 张`
            : `共 ${total.toLocaleString()} 张图片`}
        </span>

        {/* "Select all matching filter" — visible whenever the user has
            selected something but not yet covered the full filtered set. */}
        {onSelectAll && total > selectedIds.size && (
          selectedIds.size > 0 || allImages.length < total
        ) && (
          <button
            onClick={handleSelectAllMatching}
            disabled={selectingAll}
            className="text-[11.5px] text-accent hover:underline disabled:opacity-50 inline-flex items-center gap-1 whitespace-nowrap"
          >
            {selectingAll && <Loader2 size={11} className="animate-spin" />}
            选中全部 {total.toLocaleString()} 张（含未加载）
          </button>
        )}

        {/* Row-height zoom slider */}
        <div className="ml-auto flex items-center gap-1.5 text-foreground/45">
          <button
            onClick={() => setRowHeight((h) => Math.max(ROW_HEIGHT_MIN, h - ROW_HEIGHT_STEP))}
            disabled={rowHeight <= ROW_HEIGHT_MIN}
            className="h-6 w-6 rounded hover:bg-foreground/[0.05] flex items-center justify-center disabled:opacity-30"
            title="缩小"
          >
            <Minus size={12} />
          </button>
          <input
            type="range"
            min={ROW_HEIGHT_MIN}
            max={ROW_HEIGHT_MAX}
            step={ROW_HEIGHT_STEP}
            value={rowHeight}
            onChange={(e) => setRowHeight(Number(e.target.value))}
            className="w-24 h-1 accent-accent"
            title={`行高 ${rowHeight}px`}
          />
          <button
            onClick={() => setRowHeight((h) => Math.min(ROW_HEIGHT_MAX, h + ROW_HEIGHT_STEP))}
            disabled={rowHeight >= ROW_HEIGHT_MAX}
            className="h-6 w-6 rounded hover:bg-foreground/[0.05] flex items-center justify-center disabled:opacity-30"
            title="放大"
          >
            <Plus size={12} />
          </button>
        </div>
      </div>

      {/* Justified rows fill the parent's width — parent handles vertical scroll. */}
      <JustifiedGrid
        images={allImages}
        targetRowHeight={rowHeight}
        gap={8}
        selectedIds={selectedIds}
        activeId={activeId}
        selectionMode={selectionMode}
        onClickImage={onClickImage}
        onDoubleClickImage={onDoubleClickImage}
        onToggleSelect={onToggleSelect}
      />

      {hasNextPage && (
        <LoadMoreTrigger onVisible={() => fetchNextPage()} />
      )}
    </div>
  )
}

/** Intersection observer trigger to load more pages */
function LoadMoreTrigger({ onVisible }: { onVisible: () => void }) {
  const ref = useRef<HTMLDivElement>(null)
  useEffect(() => {
    const el = ref.current
    if (!el) return
    const obs = new IntersectionObserver(
      ([entry]) => { if (entry.isIntersecting) onVisible() },
      { rootMargin: '300px' },
    )
    obs.observe(el)
    return () => obs.disconnect()
  }, [onVisible])
  return <div ref={ref} className="h-4" />
}
