"""Cross-dialect JSON column accessors.

SQLite uses `json_extract(col, '$.key')`; PostgreSQL uses `col ->> 'key'`.
This module exposes one helper that picks the right SQL based on
sidecar.config.DB_DIALECT, so router code stays portable.

Usage:
    from sidecar.db.json_ops import json_field
    query = query.where(json_field(Image.generation_metadata, "prompt_id") == pid)
"""
from __future__ import annotations

from sqlalchemy import func
from sqlalchemy.sql import ColumnElement

from sidecar.config import DB_DIALECT


def json_field(column: ColumnElement, key: str) -> ColumnElement:
    """Extract a top-level key from a JSON column as text.

    Both backends return TEXT (== Python str), so equality compares with
    Python strings work the same way on either side.
    """
    if DB_DIALECT == "postgresql":
        # PG: col ->> 'key' returns text. Generated by SQLAlchemy as a
        # JSONB op so it works on both `json` and `jsonb` columns.
        return column.op("->>")(key)
    # SQLite: json_extract returns the typed value as text/number/null.
    # Always coerce to text downstream by string compare in the caller.
    return func.json_extract(column, f"$.{key}")
